### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ksallberg** [exosite/ecql2#4]
Can this library be used standalone? I tried following the steps made in interactive.sh, loading the app, setting an env var, starting. But ecql just wanted to connect to 1.2.3.4 no matter what I tried. Did I miss something simple?

**Comment by sauvainr** [comment]
@dominicletz @colachengexo might know.

**Comment by ksallberg** [comment]
I personally will not use this lib, and therefore I close the issue. It is still not really clear to me how this should be used.

**Comment by dominicletz** [comment]
Hi @ksallberg, not sure what you mean with standalone usage - maybe you can explain your use case a bit more.  But this library can be used from any Erlang or Elixir application. In case of Erlang just use rebar3 or for Elixir hex https://hex.pm/packages/ecql

The configuration is driven from application configuration. So in Erlang your applications sys.config, in Elixir your config.exs or even directly just using the application:set_env method before the app starts. All configuration variables including their defaults you can also find here: https://github.com/exosite/ecql2/blob/master/src/ecql.app.src

Hope this helps.
